<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>ConsoleUserInteractionHelper</PackageId>
    <Version>4.2.0</Version>
    <Authors>Piotr Falkowski</Authors>
    <Company>Piotr Falkowski</Company>
    <Copyright>Piotr Falkowski © 2026</Copyright>
    <Description>ConsoleHelper is a versatile .NET library designed to simplify console-based user interactions in your applications. It provides a rich set of methods to handle various input scenarios, from simple string inputs to complex numeric constraints. Prompt a user to GetNaturalInt, GetPathFromUser, GetBinaryDecisionFromUser, ShowSpinnerUntilConditionTrue to show spinner progress control in console and many others.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/PFalkowski/ConsoleUserInteractionHelper</PackageProjectUrl>
    <RepositoryUrl>https://github.com/PFalkowski/ConsoleUserInteractionHelper</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Console,Input-Output,helper</PackageTags>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\Readme.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ConsoleUserInteractionHelper.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Goblinfactory.Konsole" Version="6.2.2" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="ProgressReporting" Version="2.2.0" />
  </ItemGroup>

</Project>
